version: '2'
services:
  planner:
    container_name: planner-container
    image: planner-image
    build:
      context: .
    volumes:
      - ./:/log
      - ./:/var/app
    env_file: ./variables.env
    environment:
      - NODE_ENV=development
    ports:
      - "9122:9122"
  mongodb:
    #volumes:
    #- ${LOGGER_DATA_DIR}:/data/db
     ports:
       - 27017:27017
     image: mongo:latest
  userdata:
    container_name: user-data-container
    image: user-data-image
    env_file: ../orchestrator/variables.env
    environment:
      - NODE_ENV=development
    ports:
      - "9300:9300"
    command: npm start
  dbgateway:
    container_name: dbgateway-container
    image: dbgateway-image
    env_file: ../dbGateWay/variables.env
    environment:
      - NODE_ENV=development
    ports:
      - "9600:9600"
    command: npm start